name: Use hello-world-docker-action
on:
  push:
  workflow_dispatch:
jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Call Docker action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'NB27125'

      - name: Output from docker container
        run: echo "The time was ${{ steps.hello-action.time }} when the action returned hello"
